### ISSUE TITLE
orte_create_session_dirs is set to false.

### ISSUE THREAD

**Issue by sphcn** [geodynamics/axisem#30]
When I run 'tail -f iasp91_mrr_50s_gauss_1800s_SC_201103131137258_6.1' in step 12, a problem as below happened.

orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

You can avoid this message by specifying -quiet on the mpirun command 

  After I add the '-quiet' to mpirun and rebuild the project, this problem is still there, how do I fix it?  Any suggestions? Thanks!

**Comment by sphcn** [comment]
When I change the SAMPLING_PERIOD 0.0 to 0.02 in SOLVER/inparam_advanced, the problem above happened. And when I change the value to defaults 0.0, the problem went away. Is that a bug? How can I get the equally spaced sampling seismograms?

**Comment by martinvandriel** [comment]
sorry for the late reply. I would guess this is because SAMPLING_PERIOD you chose is smaller than the time step (0.239 for iasp91 at 50s). It produces a decent error message though:
```
219 ERROR on all ranks, error message:
220 
221  seismogram sampling cannot be smaller than time step... ^M
222  seismogram sampling:     2.0000000000000000E-002 \ nsimulation time step:   0.23908592977915313
```

So I guess you need to work on your MPI environment.

To do upsampling, you need to do some postprocessing, or use the new Instaseis (www.instaseis.net).
